version: '3'
services: 
  react: 
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: menu_frontend
    tty: true
    volumes: 
      - ./app/frontend/menu-app-frontend:/app/frontend/menu-app-frontend
    command: sh -c "npm start"
    ports:
      - 3000:3000
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: menu_backend
    tty: true
    ports: 
      - 3030:3030
  nginx:
    image: nginx
    container_name: menu_reverse_proxy
    ports: 
      - 80:80
    environment: 
      - TZ=Asia/Tokyo
    volumes: 
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://admin:${MONGODB_PASSWORD}@mongo:27017/


