version: '3'
services: 
  react: 
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: react_container
    tty: true
    volumes: 
      - ./app/frontend/menu-app-frontend:/app/frontend/menu-app-frontend
    command: sh -c "npm start"
    ports:
      - 3000:3000
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go_container
    tty: true
    ports: 
      - 3030:3030