version: '3'
services:
  nginx:
    image: nginx
    container_name: menu_reverse_proxy
    ports: 
      - 80:80
    environment: 
      - TZ=Asia/Tokyo
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - menu_frontend_net
      - menu_backend_net
networks:
  menu_frontend_net:
    external: true
  menu_backend_net:
    external: true